In [1]:
import glob
import numpy as np
import pandas as pd 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json 

import certifi
import ssl
import geopy.geocoders
from geopy.geocoders import Nominatim 
ctx = ssl.create_default_context(cafile=certifi.where())
geopy.geocoders.options.default_ssl_context = ctx

import requests 
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium # map rendering library


In [2]:

path = r'Venues' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=0, header=0)
    li.append(df)

df_venues = pd.concat(li, axis=0, ignore_index=False)
df_venues.shape

(44306, 7)

In [3]:
# df_venues.to_csv('venues.csv')

In [4]:
# df_venues = pd.read_csv('venues.csv',index_col=0, header=0)
df_venues.head()


Address  Suburb Latitude  Suburb Longitude  \
0  Ashok Vihar, New Delhi India        28.699453         77.184826   
1  Ashok Vihar, New Delhi India        28.699453         77.184826   
2  Ashok Vihar, New Delhi India        28.699453         77.184826   
3  Ashok Vihar, New Delhi India        28.699453         77.184826   
4       Bawana, New Delhi India        28.799660         77.032885   

                           Venue  Venue Latitude  Venue Longitude  \
0  Green Chick Chop, Deep Market       28.701142        77.186672   
1                    Bakers Stop       28.700495        77.188716   
2             Invitation Banquet       28.696018        77.185953   
3                  Gola Northend       28.701242        77.189288   
4           Rajiv Gandhi Stadium       28.801811        77.028751   

      Venue Category  
0            Butcher  
1             Bakery  
2              Diner  
3  Indian Restaurant  
4         Playground

In [5]:
# number of venues were returned for each neighborhood
# df_venues.groupby('Address').count()

In [6]:
# number of unique categories can be curated from all the returned venues
print('There are {} uniques categories.'.format(len(df_venues['Venue Category'].unique())))

There are 577 uniques categories.


In [60]:
# Analyze Each Address

# one hot encoding
venues_onehot = pd.get_dummies(df_venues[['Venue Category']], prefix="", prefix_sep="")

# add Address column back to dataframe
venues_onehot['Address'] = df_venues['Address']

# move Address column to the first column
fixed_columns = [venues_onehot.columns[-1]] + list(venues_onehot.columns[:-1])
venues_onehot = venues_onehot[fixed_columns]
print(venues_onehot.shape)
venues_onehot.head()

(44306, 578)


0                  0   
3                      0            0             0                  0   
4                      0            0             0                  0   

   Pakistani Restaurant  Palace  Paper / Office Supplies Store  Park  Parking  \
0                     0       0                              0     0        0   
1                     0       0                              0     0        0   
2                     0       0                              0     0        0   
3                     0       0                              0     0        0   
4                     0       0                              0     0        0   

   Pastry Shop  Pedestrian Plaza  Peking Duck Restaurant  \
0            0                 0                       0   
1            0                 0                       0   
2            0                 0                       0   
3            0                 0                       0   
4            0                 0                       0   

   Performing Arts Venue  Persian Restaurant  Peruvian Restaurant  Pet Café  \
0                      0                   0                    0         0   
1                      0                   0                    0         0   
2                      0                   0                    0         0   
3                      0                   0                    0         0   
4                      0                   0                    0         0   

   Pet Service  Pet Store  Pharmacy  Photography Studio  Physical Therapist  \
0            0          0         0                   0                   0   
1            0          0         0                   0                   0   
2            0          0         0                   0                   0   
3            0          0         0                   0                   0   
4            0          0         0                   0                   0   

   Piano Bar  Pie Shop  Pier  Piercing Parlor  Pilates Studio  Pizza Place  \
0          0         0     0                0               0            0   
1          0         0     0                0               0            0   
2          0         0     0                0               0            0   
3          0         0     0                0               0            0   
4          0         0     0                0               0            0   

   Planetarium  Platform  Playground  Plaza  Poke Place  Polish Restaurant  \
0            0         0           0      0           0                  0   
1            0         0           0      0           0                  0   
2            0         0           0      0           0                  0   
3            0         0           0      0           0                  0   
4            0         0           1      0           0                  0   

   Pool  Pool Hall  Portuguese Restaurant  Post Office  Print Shop  Pub  \
0     0          0                      0            0           0    0   
1     0          0                      0            0           0    0   
2     0          0                      0            0           0    0   
3     0          0                      0            0           0    0   
4     0          0                      0            0           0    0   

   Public Art  Punjabi Restaurant  RV Park  Racecourse  Racetrack  \
0           0                   0        0           0          0   
1           0                   0        0           0          0   
2           0                   0        0           0          0   
3           0                   0        0           0          0   
4           0                   0        0           0          0   

   Ramen Restaurant  Record Shop  Recording Studio  Recreation Center  \
0                 0            0                 0                  0   
1                 0            0                 0                  0   
2     

In [61]:
# group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
venues_grouped = venues_onehot.groupby('Address').mean().reset_index()
print(venues_grouped.shape)
venues_grouped.head()


(1117, 578)


0.0         0.00          0.00                0.0   

   Pakistani Restaurant  Palace  Paper / Office Supplies Store      Park  \
0                   0.0     0.0                            0.0  0.081081   
1                   0.0     0.0                            0.0  0.041667   
2                   0.0     0.0                            0.0  0.012500   
3                   0.0     0.0                            0.0  0.020000   
4                   0.0     0.0                            0.0  0.083333   

   Parking  Pastry Shop  Pedestrian Plaza  Peking Duck Restaurant  \
0      0.0          0.0              0.00                     0.0   
1      0.0          0.0              0.00                     0.0   
2      0.0          0.0              0.00                     0.0   
3      0.0          0.0              0.01                     0.0   
4      0.0          0.0              0.00                     0.0   

   Performing Arts Venue  Persian Restaurant  Peruvian Restaurant  Pet Café  \
0                    0.0            0.000000                  0.0       0.0   
1                    0.0            0.010417                  0.0       0.0   
2                    0.0            0.000000                  0.0       0.0   
3                    0.0            0.000000                  0.0       0.0   
4                    0.0            0.000000                  0.0       0.0   

   Pet Service  Pet Store  Pharmacy  Photography Studio  Physical Therapist  \
0          0.0       0.00   0.00000                 0.0                 0.0   
1          0.0       0.00   0.03125                 0.0                 0.0   
2          0.0       0.00   0.02500                 0.0                 0.0   
3          0.0       0.01   0.02000                 0.0                 0.0   
4          0.0       0.00   0.00000                 0.0                 0.0   

   Piano Bar  Pie Shop  Pier  Piercing Parlor  Pilates Studio  Pizza Place  \
0        0.0       0.0   0.0              0.0             0.0     0.027027   
1        0.0       0.0   0.0              0.0             0.0     0.031250   
2        0.0       0.0   0.0              0.0             0.0     0.012500   
3        0.0       0.0   0.0              0.0             0.0     0.040000   
4        0.0       0.0   0.0              0.0             0.0     0.000000   

   Planetarium  Platform  Playground   Plaza  Poke Place  Polish Restaurant  \
0          0.0  0.054054         0.0  0.0000         0.0                0.0   
1          0.0  0.000000         0.0  0.0000         0.0                0.0   
2          0.0  0.000000         0.0  0.0125         0.0                0.0   
3          0.0  0.000000         0.0  0.0100         0.0                0.0   
4          0.0  0.041667         0.0  0.0000         0.0                0.0   

   Pool  Pool Hall  Portuguese Restaurant  Post Office  Print Shop       Pub  \
0   0.0        0.0                 0.0000          0.0         0.0  0.054054   
1   0.0        0.0                 0.0000          0.0         0.0  0.041667   
2   0.0        0.0                 0.0125          0.0         0.0  0.162500   
3   0.0        0.0                 0.0300          0.0         0.0  0.010000   
4   0.0        0.0                 0.0000          0.0         0.0  0.291667   

   Public Art  Punjabi Restaurant  RV Park  Racecourse  Racetrack  \
0         0.0                 0.0      0.0         0.0   0.027027   
1         0.0                 0.0      0.0         0.0   0.000000   
2         0.0                 0.0      0.0         0.0   0.000000   
3         0.0                 0.0      0.0         0.0   0.000000   
4         0.0                 0.0      0.0         0.0   0.000000   

   Ramen Restaurant  Record Shop  Recording Studio  Recreation Center  \
0               0.0          0.0               0.0                0.0   
1               0.0          0.0               0.0                0.0   
2               0.0          0.0               0.0               

In [62]:
# venues_grouped.to_csv('venues_grouped.csv')

In [63]:
# sort the venues in descending order.

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

# create a new dataframe and display the top 10 venues for each Suburb
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Address']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
suburbs_venues_sorted = pd.DataFrame(columns=columns)
suburbs_venues_sorted['Address'] = venues_grouped['Address']

for ind in np.arange(venues_grouped.shape[0]):
    suburbs_venues_sorted.iloc[ind, 1:] = return_most_common_venues(venues_grouped.iloc[ind, :], num_top_venues)

suburbs_venues_sorted.head()

Address 1st Most Common Venue  \
0   Barking and Dagenham, London UK         Grocery Store   
1                 Barnet, London UK           Coffee Shop   
2                 Bexley, London UK                   Pub   
3                  Brent, London UK           Coffee Shop   
4                Bromley, London UK                   Pub   

  2nd Most Common Venue 3rd Most Common Venue    4th Most Common Venue  \
0           Supermarket                  Park                 Platform   
1           Supermarket                  Café       Turkish Restaurant   
2         Grocery Store           Supermarket     Fast Food Restaurant   
3        Sandwich Place     Indian Restaurant            Grocery Store   
4           Supermarket                  Park  Fruit & Vegetable Store   

  5th Most Common Venue 6th Most Common Venue  \
0              Bus Stop           Gas Station   
1                   Pub    Italian Restaurant   
2           Coffee Shop    Italian Restaurant   
3        Clothing Store                 Hotel   
4                  Lake    Turkish Restaurant   

             7th Most Common Venue   8th Most Common Venue  \
0                              Pub  Furniture / Home Store   
1                             Park             Pizza Place   
2                   Clothing Store                   Hotel   
3                      Pizza Place    Gym / Fitness Center   
4  Molecular Gastronomy Restaurant             Coffee Shop   

   9th Most Common Venue 10th Most Common Venue  
0                   Café          Shopping Mall  
1               Pharmacy          Grocery Store  
2    American Restaurant      Indian Restaurant  
3  Portuguese Restaurant               Pharmacy  
4   Fast Food Restaurant               Platform

In [64]:
# suburbs_venues_sorted.to_csv('venues_sorted.csv')

In [65]:
# Cluster Suburbs

# set number of clusters
kclusters = 10

venues_grouped_clustering = venues_grouped.drop('Address', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(venues_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_

array([2, 2, 2, ..., 2, 5, 2], dtype=int32)

In [66]:
# dataframe that includes the cluster as well as the top 10 venues for each Suburb

# add clustering labels
suburbs_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)
# merge venues_grouped with venues data to add latitude/longitude for each Suburb
venues_merged = suburbs_venues_sorted.join(df_venues.set_index('Address'), on='Address')
venues_merged.shape # check the last columns!

(44306, 18)

In [67]:
venues_merged[['Suburb','Region']] = venues_merged.Address.str.split(", ", expand=True)
cols = venues_merged.columns.tolist()
cols = cols[:2] + cols[-2:] + cols[2:-2]
venues_merged = venues_merged[cols]
venues_merged.head()

Cluster Labels                           Address                 Suburb  \
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   

      Region 1st Most Common Venue 2nd Most Common Venue  \
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   

  6th Most Common Venue 7th Most Common Venue   8th Most Common Venue  \
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   

  9th Most Common Venue 10th Most Common Venue  Suburb Latitude  \
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   

   Suburb Longitude                        Venue  Venue Latitude  \
0          0.150504                 Central Park       51.559560   
0          0.150504                   Lara Grill       51.562445   
0          0.150504                        wilko       51.541002   
0          0.150504                     Hoo Hing       51.567561   
0          0.150504  The Eva Hart  (Wetherspoon)       51.570460   

   Venue Longitude          Venue Category  
0         0.161981                    Park  
0         0.147178      Turkish Restaurant  
0         0.148898  Furniture / Home Store  
0         0.135999           Grocery Store  
0         0.130342                     Pub

In [68]:
regions = venues_merged['Region'].unique()
for region in regions:
    index = venues_merged[venues_merged['Region']==region]
    print(region)
    print(index['Cluster Labels'].unique())

London UK
[2 1]
Brisbane
[2 5 6 3 8 1 0 9 4]
Tokyo Japan
[2 5]
Christchurch New Zealand
[5 9 2 6 1 3]
Mumbai City India
[2 5 9]
Sydney
[5 2]
New York City US
[2 9 6 5 1 4 3]
New Delhi India
[1 5 2 9 7 0]
Beijing China
[5 1 2]
Los Angeles US
[2 9 5 3 0 4 1]
Auckland City New Zealand
[5 1 2 9]
Hanoi Vietnam
[2 5 1]
Kathmandu Nepal
[1]
Kuala Lumpur Malaysia
[2 5]
Shanghai China
[1 2 9]
Melbourne
[5 2]


In [69]:
venues_merged.to_csv('venues_merged.csv')

In [70]:
df = venues_merged.drop(columns=['Venue','Venue Latitude','Venue Longitude','Venue Category'])
df.head()

Cluster Labels                           Address                 Suburb  \
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   
0               2   Barking and Dagenham, London UK   Barking and Dagenham   

      Region 1st Most Common Venue 2nd Most Common Venue  \
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   
0  London UK         Grocery Store           Supermarket   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   
0                  Park              Platform              Bus Stop   

  6th Most Common Venue 7th Most Common Venue   8th Most Common Venue  \
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   
0           Gas Station                   Pub  Furniture / Home Store   

  9th Most Common Venue 10th Most Common Venue  Suburb Latitude  \
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   
0                  Café          Shopping Mall        51.554117   

   Suburb Longitude  
0          0.150504  
0          0.150504  
0          0.150504  
0          0.150504  
0          0.150504

In [71]:
def clusterMap(address, vLatitude_col, vLongitude_col, address_col, clusterLabel_col, zoom_start):

    geolocator = Nominatim(user_agent="explorer")
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    print('The geograpical coordinate of {} are {}, {}.'.format(address, latitude, longitude))

    # create map
    map_clusters = folium.Map(location=[latitude, longitude], zoom_start=zoom_start)

    # set color scheme for the clusters
    x = np.arange(kclusters)
    ys = [i + x + (i*x)**2 for i in range(kclusters)]
    colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
    rainbow = [colors.rgb2hex(i) for i in colors_array]

    # add markers to the map
    markers_colors = []
    for lat, lon, poi, cluster in zip(vLatitude_col, vLongitude_col, address_col, clusterLabel_col):
        label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
        folium.CircleMarker(
            [lat, lon],
            radius=5,
            popup=label,
            color=rainbow[cluster-1],
            fill=True,
            fill_color=rainbow[cluster-1],
            fill_opacity=0.7).add_to(map_clusters)
        
    return(map_clusters)

In [72]:
index = venues_merged[venues_merged['Region']=='Sydney']
clusterMap('City of Sydney, Australia', index['Venue Latitude'], index['Venue Longitude'], index['Address'], index['Cluster Labels'], 12)

The geograpical coordinate of City of Sydney, Australia are -33.8853222, 151.2065221.
