In [6]:
import glob
import numpy as np
import pandas as pd 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json 

import certifi
import ssl
import geopy.geocoders
from geopy.geocoders import Nominatim 
ctx = ssl.create_default_context(cafile=certifi.where())
geopy.geocoders.options.default_ssl_context = ctx

import requests 
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium # map rendering library

In [7]:
venues_grouped = pd.read_csv('venues_grouped.csv', index_col=0)
suburbs_venues_sorted = pd.read_csv('venues_sorted.csv', index_col=0)
venues_grouped.head()

0.0         0.00          0.00                0.0   

   Pakistani Restaurant  Palace  Paper / Office Supplies Store      Park  \
0                   0.0     0.0                            0.0  0.081081   
1                   0.0     0.0                            0.0  0.041667   
2                   0.0     0.0                            0.0  0.012500   
3                   0.0     0.0                            0.0  0.020000   
4                   0.0     0.0                            0.0  0.083333   

   Parking  Pastry Shop  Pedestrian Plaza  Peking Duck Restaurant  \
0      0.0          0.0              0.00                     0.0   
1      0.0          0.0              0.00                     0.0   
2      0.0          0.0              0.00                     0.0   
3      0.0          0.0              0.01                     0.0   
4      0.0          0.0              0.00                     0.0   

   Performing Arts Venue  Persian Restaurant  Peruvian Restaurant  Pet Café  \
0                    0.0            0.000000                  0.0       0.0   
1                    0.0            0.010417                  0.0       0.0   
2                    0.0            0.000000                  0.0       0.0   
3                    0.0            0.000000                  0.0       0.0   
4                    0.0            0.000000                  0.0       0.0   

   Pet Service  Pet Store  Pharmacy  Photography Studio  Physical Therapist  \
0          0.0       0.00   0.00000                 0.0                 0.0   
1          0.0       0.00   0.03125                 0.0                 0.0   
2          0.0       0.00   0.02500                 0.0                 0.0   
3          0.0       0.01   0.02000                 0.0                 0.0   
4          0.0       0.00   0.00000                 0.0                 0.0   

   Piano Bar  Pie Shop  Pier  Piercing Parlor  Pilates Studio  Pizza Place  \
0        0.0       0.0   0.0              0.0             0.0     0.027027   
1        0.0       0.0   0.0              0.0             0.0     0.031250   
2        0.0       0.0   0.0              0.0             0.0     0.012500   
3        0.0       0.0   0.0              0.0             0.0     0.040000   
4        0.0       0.0   0.0              0.0             0.0     0.000000   

   Planetarium  Platform  Playground   Plaza  Poke Place  Polish Restaurant  \
0          0.0  0.054054         0.0  0.0000         0.0                0.0   
1          0.0  0.000000         0.0  0.0000         0.0                0.0   
2          0.0  0.000000         0.0  0.0125         0.0                0.0   
3          0.0  0.000000         0.0  0.0100         0.0                0.0   
4          0.0  0.041667         0.0  0.0000         0.0                0.0   

   Pool  Pool Hall  Portuguese Restaurant  Post Office  Print Shop       Pub  \
0   0.0        0.0                 0.0000          0.0         0.0  0.054054   
1   0.0        0.0                 0.0000          0.0         0.0  0.041667   
2   0.0        0.0                 0.0125          0.0         0.0  0.162500   
3   0.0        0.0                 0.0300          0.0         0.0  0.010000   
4   0.0        0.0                 0.0000          0.0         0.0  0.291667   

   Public Art  Punjabi Restaurant  RV Park  Racecourse  Racetrack  \
0         0.0                 0.0      0.0         0.0   0.027027   
1         0.0                 0.0      0.0         0.0   0.000000   
2         0.0                 0.0      0.0         0.0   0.000000   
3         0.0                 0.0      0.0         0.0   0.000000   
4         0.0                 0.0      0.0         0.0   0.000000   

   Ramen Restaurant  Record Shop  Recording Studio  Recreation Center  \
0               0.0          0.0               0.0                0.0   
1               0.0          0.0               0.0                0.0   
2               0.0          0.0               0.0               

In [8]:
# Cluster Suburbs

# set number of clusters
kclusters = 5

venues_grouped_clustering = venues_grouped.drop('Address', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(venues_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_

array([0, 0, 0, ..., 0, 3, 0], dtype=int32)

In [9]:
# dataframe that includes the cluster as well as the top 10 venues for each Suburb

# add clustering labels
suburbs_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)
# merge venues_grouped with venues data to add latitude/longitude for each Suburb
venues_merged = suburbs_venues_sorted.join(df_venues.set_index('Address'), on='Address')
venues_merged.shape # check the last columns!

NameError: name 'df_venues' is not defined

In [5]:
# venues_merged = pd.read_csv('venues_merged.csv')
# venues_merged.shape


In [6]:
regions = venues_merged['Region'].unique()
for region in regions:
    index = venues_merged[venues_merged['Region']==region]
    print(region)
    print(index['Cluster Labels'].unique())


London UK
[0]
Brisbane
[0 3 2 1]
Tokyo Japan
[0 3]
Christchurch New Zealand
[3 1 0 2]
Mumbai City India
[0 3 2 1]
Sydney
[3 0]
New York City US
[0 1 2 3]
New Delhi India
[0 3 2 1 4]
Beijing China
[3 0]
Los Angeles US
[0 1 3]
Auckland City New Zealand
[3 0 2 1]
Hanoi Vietnam
[0 3]
Kathmandu Nepal
[0 3]
Kuala Lumpur Malaysia
[0 3 2]
Shanghai China
[0 1]
Melbourne
[3 0]


In [17]:
kclusters = 5
def clusterMap(address, vLatitude_col, vLongitude_col, address_col, clusterLabel_col, zoom_start):

    geolocator = Nominatim(user_agent="explorer")
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    print('The geograpical coordinate of {} are {}, {}.'.format(address, latitude, longitude))

    # create map
    map_clusters = folium.Map(location=[latitude, longitude], zoom_start=zoom_start)

    # set color scheme for the clusters
    x = np.arange(kclusters)
    ys = [i + x + (i*x)**2 for i in range(kclusters)]
    colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
    rainbow = [colors.rgb2hex(i) for i in colors_array]

    # add markers to the map
    markers_colors = []
    for lat, lon, poi, cluster in zip(vLatitude_col, vLongitude_col, address_col, clusterLabel_col):
        label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
        folium.CircleMarker(
            [lat, lon],
            radius=5,
            popup=label,
            color=rainbow[cluster-1],
            fill=True,
            fill_color=rainbow[cluster-1],
            fill_opacity=0.7).add_to(map_clusters)
        
    return(map_clusters)

In [18]:
for region in regions:
    index = venues_merged[venues_merged['Region']==region]
    clusterMap(region, index['Venue Latitude'], index['Venue Longitude'], index['Address'], index['Cluster Labels'], 12)

The geograpical coordinate of London UK are 51.5073219, -0.1276474.
The geograpical coordinate of Brisbane are -27.4689682, 153.0234991.
The geograpical coordinate of Tokyo Japan are 55.7746222, 37.6326806.
The geograpical coordinate of Christchurch New Zealand are -43.530955, 172.6366455.
The geograpical coordinate of Mumbai City India are 18.9733536, 72.82810491917377.
The geograpical coordinate of Sydney are -33.8548157, 151.2164539.
The geograpical coordinate of New York City US are 40.7127281, -74.0060152.
The geograpical coordinate of New Delhi India are 28.6141793, 77.2022662.
The geograpical coordinate of Beijing China are 39.906217, 116.3912757.
The geograpical coordinate of Los Angeles US are 34.0536909, -118.2427666.
The geograpical coordinate of Auckland City New Zealand are -36.852095, 174.7631803.
The geograpical coordinate of Hanoi Vietnam are 21.0294498, 105.8544441.
The geograpical coordinate of Kathmandu Nepal are 27.708317, 85.3205817.
The geograpical coordinate of K